config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :skills
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :project_profiles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "page#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project_profile.rb
# frozen_string_literal: true

class ProjectProfile < ApplicationRecord
  has_many :skill_requirements
  has_many :skills, through: :skill_requirements

  belongs_to :user
  validates :name, presence: true
end

app/models/skill.rb
class Skill < ApplicationRecord
  validates :name, presence: true
end

app/models/skill_requirement.rb
class SkillRequirement < ApplicationRecord
  belongs_to :project_profile
  belongs_to :skill
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[github]

  has_many :project_profiles

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  after_action :verify_authorized, unless: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are unauthorized to perform this action."
    redirect_to(request.referrer || new_user_session_path)
  end
end

app/controllers/page_controller.rb
# frozen_string_literal: true

class PageController < ApplicationController
  def home
    authorize :page, :home?
  end
end

app/controllers/project_profiles_controller.rb
# frozen_string_literal: true

class ProjectProfilesController < ApplicationController
  before_action :set_project_profile, only: %i[show edit update destroy]

  # GET /project_profiles
  # GET /project_profiles.json
  def index
    authorize ProjectProfile
    @project_profiles = policy_scope(ProjectProfile)
  end

  # GET /project_profiles/1
  # GET /project_profiles/1.json
  def show
    authorize ProjectProfile
  end

  # GET /project_profiles/new
  def new
    @project_profile = ProjectProfile.new
    authorize @project_profile
  end

  # GET /project_profiles/1/edit
  def edit
    authorize @project_profile
  end

  # POST /project_profiles
  # POST /project_profiles.json
  def create
    @project_profile = ProjectProfile.new(project_profile_params)
    @project_profile.user = current_user
    authorize @project_profile
    respond_to do |format|
      if @project_profile.save
        format.html { redirect_to @project_profile, notice: "Project profile was successfully created." }
        format.json { render :show, status: :created, location: @project_profile }
      else
        format.html { render :new }
        format.json { render json: @project_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_profiles/1
  # PATCH/PUT /project_profiles/1.json
  def update
    authorize @project_profile
    respond_to do |format|
      if @project_profile.update(project_profile_params)
        format.html { redirect_to @project_profile, notice: "Project profile was successfully updated." }
        format.json { render :show, status: :ok, location: @project_profile }
      else
        format.html { render :edit }
        format.json { render json: @project_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_profiles/1
  # DELETE /project_profiles/1.json
  def destroy
    authorize @project_profile
    @project_profile.destroy
    respond_to do |format|
      format.html { redirect_to project_profiles_url, notice: "Project profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project_profile
    @project_profile = ProjectProfile.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_profile_params
    params.require(:project_profile).permit(:name, :short_description, :domain_introduction, :project_link, skill_ids: [])
  end
end

app/controllers/skills_controller.rb
# frozen_string_literal: true

class SkillsController < ApplicationController
  before_action :set_skill, only: %i[show edit update destroy]

  # GET /skills
  # GET /skills.json
  def index
    authorize Skill
    @skills = policy_scope(Skill)
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
    authorize Skill
  end

  # GET /skills/new
  def new
    @skill = Skill.new
    authorize @skill
  end

  # GET /skills/1/edit
  def edit
    authorize @skill
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)
    authorize @skill

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: "Skill was successfully created." }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    authorize @skill

    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: "Skill was successfully updated." }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    authorize @skill

    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: "Skill was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_skill
    @skill = Skill.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def skill_params
    params.require(:skill).permit(:name)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      if is_navigational_format?
        set_flash_message(:notice, :success, kind: "Github")
      end
    else
      # session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/project_profiles_helper.rb
module ProjectProfilesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>NeedEngineer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
  </body>
</html>

app/views/page/home.html.erb
<div class="jumbotron">
  <h1 class="display-4">NeedEngineer</h1>
  <p class="lead">Matching tech volunteers with non-profit organizations.</p>

  <div class="d-flex justify-content-between align-items-stretch flex-wrap">
    <%= link_to "Find a project", project_profiles_path, class: "btn btn-primary btn-lg flex-grow-1 mr-2" %>
    <%= link_to "Register a project", new_project_profile_path, class: "btn btn-primary btn-lg flex-grow-1" %>
  </div>
</div>

app/views/project_profiles/_form.html.erb
<%= form_with(model: project_profile, local: true) do |form| %>
  <% if project_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project_profile.errors.count, "error") %> prohibited this project_profile from being saved:</h2>

      <ul>
        <% project_profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :short_description %>
    <%= form.text_area :short_description %>
  </div>

  <div class="field">
    <%= form.label :domain_introduction %>
    <%= form.text_area :domain_introduction %>
  </div>

  <div class="field">
    <%= form.label :skill_requirements %>
    <%= form.collection_check_boxes(:skill_ids, Skill.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :project_link %>
    <%= form.url_field :project_link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/project_profiles/edit.html.erb
<h1>Editing Project Profile</h1>

<%= render "form", project_profile: @project_profile %>

<%= link_to "Show", @project_profile %> |
<%= link_to "Back", project_profiles_path %>

app/views/project_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Project Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short description</th>
      <th>Domain introduction</th>
      <th>Project link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_profiles.each do |project_profile| %>
      <tr>
        <td><%= project_profile.name %></td>
        <td><%= project_profile.short_description %></td>
        <td><%= project_profile.domain_introduction %></td>
        <td><%= project_profile.project_link %></td>
        <td><%= link_to "Show", project_profile %></td>
        <td><%= link_to "Edit", edit_project_profile_path(project_profile) %></td>
        <td><%= link_to "Destroy", project_profile, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Project Profile", new_project_profile_path %>

app/views/project_profiles/new.html.erb
<h1>New Project Profile</h1>

<%= render "form", project_profile: @project_profile %>

<%= link_to "Back", project_profiles_path %>

app/views/project_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project_profile.name %>
</p>

<p>
  <strong>Short description:</strong>
  <%= @project_profile.short_description %>
</p>

<p>
  <strong>Domain introduction:</strong>
  <%= @project_profile.domain_introduction %>
</p>

<p>
  <strong>Project link:</strong>
  <%= @project_profile.project_link %>
</p>

<%= link_to "Edit", edit_project_profile_path(@project_profile) %> |
<%= link_to "Back", project_profiles_path %>

app/views/skills/_form.html.erb
<%= form_with(model: skill, local: true) do |form| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
        <% skill.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render "form", skill: @skill %>

<%= link_to "Show", @skill %> |
<%= link_to "Back", skills_path %>

app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Skills</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.name %></td>
        <td><%= link_to "Show", skill %></td>
        <td><%= link_to "Edit", edit_skill_path(skill) %></td>
        <td><%= link_to "Destroy", skill, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Skill", new_skill_path %>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render "form", skill: @skill %>

<%= link_to "Back", skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skill.name %>
</p>

<%= link_to "Edit", edit_skill_path(@skill) %> |
<%= link_to "Back", skills_path %>